# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LibertyPoolTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LibertyPoolTest

    pod 'Charts'
    pod 'Alamofire',  '~> 4.0'
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'RappleProgressHUD'
    
  target 'LibertyPoolTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LibertyPoolTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
